-- ============================================================
-- YO PLAY BEER 🍺 — Módulo Inventario
-- SQL completo para Supabase / PostgreSQL
-- Ejecutar en el SQL Editor de Supabase, en este orden.
-- ============================================================

-- ------------------------------------------------------------
-- 1. TABLA productos
-- ------------------------------------------------------------
create table if not exists productos (
  id             bigint generated by default as identity primary key,
  nombre         text not null,
  descripcion    text,
  categoria      text,
  stock          numeric not null default 0,
  stock_minimo   numeric not null default 0,
  unidad         text not null default 'unidad',
  precio_compra  numeric,
  precio_venta   numeric,
  activo         boolean not null default true,
  created_at     timestamptz not null default now(),

  constraint productos_stock_no_negativo check (stock >= 0),
  constraint productos_stock_minimo_no_negativo check (stock_minimo >= 0),
  constraint productos_precio_compra_no_negativo check (precio_compra is null or precio_compra >= 0),
  constraint productos_precio_venta_no_negativo check (precio_venta is null or precio_venta >= 0)
);

create index if not exists idx_productos_nombre on productos (nombre);
create index if not exists idx_productos_activo on productos (activo);

-- ------------------------------------------------------------
-- 2. TABLA movimientos_inventario
-- ------------------------------------------------------------
create table if not exists movimientos_inventario (
  id              bigint generated by default as identity primary key,
  producto_id     bigint not null references productos(id) on delete cascade,
  tipo            text not null,
  cantidad        numeric not null,
  stock_anterior  numeric not null,
  stock_nuevo     numeric not null,
  motivo          text,
  created_at      timestamptz not null default now(),

  constraint movimientos_tipo_valido check (tipo in ('entrada', 'salida', 'ajuste')),
  constraint movimientos_cantidad_no_negativa check (cantidad >= 0)
);

create index if not exists idx_movimientos_producto_id on movimientos_inventario (producto_id);
create index if not exists idx_movimientos_created_at on movimientos_inventario (created_at desc);

-- ------------------------------------------------------------
-- 3. FUNCIÓN RPC: registrar_movimiento_inventario
--
-- Hace atómico el proceso de:
--   1. Leer el stock actual (con bloqueo de fila)
--   2. Calcular el stock nuevo según el tipo de movimiento
--   3. Validar que no quede stock negativo
--   4. Actualizar productos.stock
--   5. Insertar el registro en movimientos_inventario
--
-- Para 'entrada' y 'salida', p_cantidad es la cantidad a mover.
-- Para 'ajuste', p_cantidad es el STOCK NUEVO deseado (el valor
-- final), y la función calcula la diferencia para el historial.
-- ------------------------------------------------------------
create or replace function registrar_movimiento_inventario(
  p_producto_id bigint,
  p_tipo text,
  p_cantidad numeric,
  p_motivo text default null
)
returns movimientos_inventario
language plpgsql
security definer
set search_path = public
as $$
declare
  v_stock_actual numeric;
  v_stock_nuevo numeric;
  v_cantidad_historial numeric;
  v_movimiento movimientos_inventario;
begin
  if p_tipo not in ('entrada', 'salida', 'ajuste') then
    raise exception 'Tipo de movimiento inválido: %', p_tipo;
  end if;

  if p_cantidad is null or p_cantidad < 0 then
    raise exception 'La cantidad debe ser un número mayor o igual a 0';
  end if;

  select stock into v_stock_actual
  from productos
  where id = p_producto_id
  for update;

  if not found then
    raise exception 'Producto no encontrado: %', p_producto_id;
  end if;

  if p_tipo = 'entrada' then
    v_stock_nuevo := v_stock_actual + p_cantidad;
    v_cantidad_historial := p_cantidad;

  elsif p_tipo = 'salida' then
    v_stock_nuevo := v_stock_actual - p_cantidad;
    if v_stock_nuevo < 0 then
      raise exception 'Stock insuficiente. Stock actual: %, cantidad solicitada: %', v_stock_actual, p_cantidad;
    end if;
    v_cantidad_historial := p_cantidad;

  else -- ajuste: p_cantidad es el stock nuevo deseado
    v_stock_nuevo := p_cantidad;
    v_cantidad_historial := abs(v_stock_nuevo - v_stock_actual);
  end if;

  update productos
  set stock = v_stock_nuevo
  where id = p_producto_id;

  insert into movimientos_inventario (
    producto_id, tipo, cantidad, stock_anterior, stock_nuevo, motivo
  ) values (
    p_producto_id, p_tipo, v_cantidad_historial, v_stock_actual, v_stock_nuevo, p_motivo
  )
  returning * into v_movimiento;

  return v_movimiento;
end;
$$;

-- ------------------------------------------------------------
-- 4. ROW LEVEL SECURITY (opcional, recomendado)
--
-- El proyecto actual usa Supabase desde el cliente. Si tus otras
-- tablas (por ejemplo las de Mesas) ya tienen RLS habilitado con
-- políticas abiertas para desarrollo, replica el mismo criterio
-- aquí para no romper el patrón existente. Si NO estás usando RLS
-- en el resto del proyecto todavía, puedes omitir este bloque.
-- ------------------------------------------------------------
alter table productos enable row level security;
alter table movimientos_inventario enable row level security;

drop policy if exists "productos_select_all" on productos;
create policy "productos_select_all" on productos
  for select using (true);

drop policy if exists "productos_insert_all" on productos;
create policy "productos_insert_all" on productos
  for insert with check (true);

drop policy if exists "productos_update_all" on productos;
create policy "productos_update_all" on productos
  for update using (true);

drop policy if exists "productos_delete_all" on productos;
create policy "productos_delete_all" on productos
  for delete using (true);

drop policy if exists "movimientos_select_all" on movimientos_inventario;
create policy "movimientos_select_all" on movimientos_inventario
  for select using (true);

drop policy if exists "movimientos_insert_all" on movimientos_inventario;
create policy "movimientos_insert_all" on movimientos_inventario
  for insert with check (true);

-- Nota: estas políticas son permisivas (equivalentes a no tener RLS)
-- y sirven para desarrollo. Antes de producción, ajústalas a tu
-- modelo real de autenticación (por ejemplo, restringir por rol
-- de usuario autenticado).
